### ISSUE TITLE
Is that possible to release the detection demo?

### ISSUE THREAD

**Issue by semchan** [Tencent/ActionDetection-DBG#15]
Greeting! since there is only evaluation for proposals,  do you plan to release the detection code? thanks.

**Comment by semchan** [comment]
HI, I use DBG to produce the proposals from the feature's data which you provided, and then use the proposals and the TSN features directly to do the temporal detection, the result is poor, only got 0.2mPA. I wonder, the big problem is I have not use the final video-level score for detection, but use only the 100*400 feature's for detection. Is that right? and would you please give me the guide to improve the mAP based on DBG? thanks very much.


[INIT] Loaded annotations from validation subset.
	Number of ground truth instances: 7654
	Number of predictions: 472700
	Fixed threshold for tiou score: [0.5  0.55 0.6  0.65 0.7  0.75 0.8  0.85 0.9  0.95]
[RESULTS] Performance on ActivityNet detection task.
	Average-mAP: 0.20763225314731745

**Comment by happyCodingSusan** [comment]
Great work! Thank you for sharing. I also want to ask whether you could release your detection demo.

**Comment by quanh1990** [comment]
@lijiannuist Would you please release the detection demo? Thanks a lot.
I still cannot see how to get the action label and the start/end using your code for a single video.

**Comment by GeLee-Q** [comment]
请问inference model到时候会开源出来嘛，想试试能否实际的去应用一下。
